# An Ansible version of the approach defined here
# https://askubuntu.com/questions/766900/mysql-doesnt-ask-for-root-password-when-installing/766908#766908?newreg=62a1dbc4e7764281ab0b35cfd0932894
---
- name: Install python interface to mysql
  apt: name='{{ item }}' state=latest
  with_items:
    - python-mysqldb
    - python3-mysqldb

- name: Stop mysql server
  service: name=mysql state=stopped

### Temporarily override the default command for the mysql systemd service.
- name: Create mysql service override directory
  file: path=/etc/systemd/system/mysql.service.d/ state=directory
- name: Take control of the mysql service
  template:
    src: override.conf.tpl
    dest: /etc/systemd/system/mysql.service.d/root_reset_override.conf
- name: Restart modified mysql server
  service:
    name: mysql
    state: started
    daemon_reload: yes
- name: Copy password reset script
  template: src=reset-root-password.sql.tpl dest=/tmp/reset-root-password.sql
- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    name: mysql
    target: /tmp/reset-root-password.sql

### Restore the default command for the mysql systemd service.
- name: Delete password reset script
  file: path=/tmp/reset-root-password.sql state=absent
- name: Restore the mysql service to its usual mode of operation
  file:
    path: /etc/systemd/system/mysql.service.d/root_reset_override.conf
    state: absent
- name: Restart mysql server
  service: name=mysql state=restarted daemon_reload=yes
